---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Sync submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: apply patch to xonsh
          command: |
            ls
            git -C xonsh apply ../patches/add_i18n_conf.patch
      - restore_cache:
          keys:
            - venv-cache-{{ .Environment.CACHE_VALUE }}-{{ checksum "xonsh/requirements-docs.txt" }}
            - venv-cache-{{ .Environment.CACHE_VALUE }}
      - run:
          name: create venv
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r xonsh/requirements-docs.txt
            (cd xonsh && pip install -e .)
      - save_cache:
          key: venv-cache-{{ .Environment.CACHE_VALUE }}-{{ checksum "xonsh/requirements-docs.txt" }}
          paths: venv
      - run:
          name: Building docs
          command: |
            mkdir -p xonsh/docs/locale/ja
            ln -s ../../../../LC_MESSAGES xonsh/docs/locale/ja
            . venv/bin/activate
            git clone git@github.com:virusbb001/xonsh-docs-ja.git xonsh/docs/_build/html
            # git clone https://github.com/virusbb001/xonsh-docs-ja.git xonsh/docs/_build/html
            (cd xonsh/docs && make -e SPHINXOPTS="-D language='ja'" html)
      - run:
          name: Publish docs
          command: |
            cd xonsh/docs/_build/html
            git config user.email "virusbb001a+circleci@gmail.com"
            git config user.name "virus bot"
            git add .
            git commit -m "[ci skip] Publish at $(date)

            xonsh.ja.po: $CIRCLE_SHA1"
            git push origin master
            # git log -n1 -p HEAD | cat

# Orchestrate or schedule a set of jobs,
# see https://circleci.com/docs/2.0/workflows/
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /enhance-ci-.*/
  version: 2
