---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - run:
          name: Sync original xonsh
          command: git clone https://github.com/xonsh/xonsh.git
      - checkout:
          path: xonsh/docs/locale/ja
      - run:
          name: apply patch to xonsh
          command: |
            git -C xonsh apply docs/locale/ja/patches/add_i18n_conf.patch
      - run:
          name: create venv
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r xonsh/requirements-docs.txt
            (cd xonsh && pip install -e .)
      - run:
          name: Building docs
          command: |
            . venv/bin/activate
            git clone git@github.com:virusbb001/xonsh-docs-ja.git xonsh/docs/_build/html
            # git clone https://github.com/virusbb001/xonsh-docs-ja.git xonsh/docs/_build/html
            (cd xonsh/docs && make -e SPHINXOPTS="-D language='ja'" html)
      - run:
          name: Publish docs
          command: |
            cd xonsh/docs/_build/html
            git config user.email "virusbb001a+circleci@gmail.com"
            git config user.name "virus bot"
            git add .
            git commit -m "[ci skip] Publish at $(date)

            xonsh.ja.po: $CIRCLE_SHA1"
            git push origin master
            # git log -n1 HEAD

# Orchestrate or schedule a set of jobs,
# see https://circleci.com/docs/2.0/workflows/
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
  version: 2
